### ISSUE TITLE
Add php calendar extension

### ISSUE THREAD

**Issue by dbeniamine** [Monogramm/docker-dolibarr#12]
Hello,

First of all, I want to thank you for your docker dolibarr image !

I have a small issue with it : some Dolibarr features requires the calendar mod (call to `easter_date` in holiday calculations), could you add it to the docker file:
```bash
RUN docker-php-ext-configure calendar && docker-php-ext-install calendar
```

**Comment by madmath03** [comment]
@dbeniamine  Hi!

Thanks a lot for your support and for reporting this.

This is indeed a good thing to add. PR has been merged and docker hub should finish building the images in a few hours.

Enjoy 😉

**Comment by dbeniamine** [comment]
@madmath03 wow that was quick, thanks :+1:

**Comment by dbeniamine** [comment]
Hi again,

I am sorry but I forgot one step : we also need to add : `extension = calendar.so` to `/usr/local/etc/php/php.ini`

**Comment by madmath03** [comment]
@dbeniamine I can do it this really quickly of course, but I suggest you retrieve the Dockerfile, build it locally and validate it yourself.

I will merge the PR once you have confirmed that this solves your issue.

**Comment by dbeniamine** [comment]
Thanks again for your answer, I just built an tested it (version 8.0/php7.1-apache) it seems fine for me :+1:
