### ISSUE TITLE
mail campains

### ISSUE THREAD

**Issue by herrmit** [Monogramm/docker-dolibarr#26]
Hello,

perhaps I did something wrong. I created the images for dolibarr / mariadb according to the description on docker hub and then tried a mail campaign. Mail sending did not work. When I tried

php ./scripts/emailings/mailing-send.php 1 chennemann 

in the console, I get the following error message:

# php ./scripts/emailings/mailing-send.php 1 chennemann
PHP Warning:  Module 'calendar' already loaded in Unknown on line 0
***** mailing-send.php (8.0.4) pid=139 *****
Process mailing with id 1
Nb of targets = 1
sh: 1: /usr/sbin/sendmail: not found
> Error detected:
./scripts/emailings/mailing-send.php
> Database type manager:
mysqli
> Latest database access request error:
UPDATE llx_mailing_cibles SET statut=-1, date_envoi=2019-01-27 18:42:15 WHERE rowid=1
> Return code for latest database access request error:
DB_ERROR_SYNTAX
> Information for latest database access request error:
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '18:42:15 WHERE rowid=1' at line 1
Update status of emailing id 1 to 2

Looks like /usr/sbin/sendmail is missing. Right? What can I do?

Help is very much appreciated.

Regards
 Michael

**Comment by madmath03** [comment]
Hello @herrmit ,

Indeed, sendmail is not installed in this docker image, but it was choice on our side. sendmail is only used by the PHP mail function which can often be blocked by mail providers. This is why it's usually better to connect to a mail server and use it to send your emails. See documentation on email configuration for details: https://wiki.dolibarr.org/index.php/Setup_EMails#Method_to_send_emails

If you really want to use the default PHP function as the sending method, you could build your own custom image based on this one and just add what you need : 
```Dockerfile
FROM monogramm/docker-dolibarr:apache

RUN set -ex; \
	apt-get update -q; \
	apt-get install -y --no-install-recommends \
		sendmail \
	;

```

**Please be aware that the previous Dockerfile is just a sample I wrote on the fly and is not tested!**

Hope that helps solve your issue.

Best regards.

**Comment by madmath03** [comment]
Hello @herrmit,

Were you able to fix your issue ?

**Comment by madmath03** [comment]
Well, looking back on this, there is actually a mistake in our php.ini configuration where we set the sendmail path while sendmail is not installed...
sendmail isn't too big so I guess we will change our mindset and provide sendmail in this docker image.
I will update the containers and close this issue.
