### ISSUE TITLE
access after install failed 

### ISSUE THREAD

**Issue by kfr-ma** [Monogramm/docker-dolibarr#29]
Hi

I just installed the docker image via : docker run -d -p 8080:80 monogramm/docker-dolibarr when i try to access to localhost:8080 , i get the following error :

Warning: mysqli::__construct(): (HY000/2002): No such file or directory in /var/www/html/core/db/mysqli.class.php on line 203
DolibarrHasDetectedError.
InformationToHelpDiagnose:
Date: 20190312131551
Dolibarr: 9.0.0
PHP: 7.1.26
Server: Apache/2.4.25 (Debian)
OS: Linux 5eb875877037 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64
UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15

RequestedUrl: /
Referer: 
MenuManager: 

DatabaseTypeManager: mysqli
RequestLastAccessInError: ErrorNoRequestInError
ReturnCodeLastAccessInError: ErrorNoRequestInError
InformationLastAccessInError: ErrorNoRequestInError

Message: host=localhost, port=3306, user=, databasename=, No such file or directory

**Comment by madmath03** [comment]
Hello,

You need to set the database name, user and password through environment variables:
```
docker run -d -e DOLI_DB_NAME=dolibarr -e DOLI_DB_USER=dolibarr -e DOLI_DB_PASSWORD=dolibarr -p 8080:80 monogramm/docker-dolibarr
```
The docker image currently auto-configures itself based on the environment variables. If you do not provide any, it is very unlikely to work. You will need to create the user and database accordingly.

If you're not comfortable with Docker, I suggest you use the docker-compose samples provided in the [README](https://github.com/Monogramm/docker-dolibarr#running-this-image-with-docker-compose).

In the meantime, I will see how we can add a feature to disable auto-configuration but auto-configuration will still be the default behavior.
