### ISSUE TITLE
Server field required

### ISSUE THREAD

**Issue by ser-gent** [Monogramm/docker-dolibarr#44]
Hi !
I would test the image with command
`docker run -e DOLI_AUTO_CONFIGURE='' -p 8080:80 monogramm/docker-dolibarr`

The configuration started and after the db config I have the message : Server field is required but I can"t edit server field in previous page.

thanks

**Comment by madmath03** [comment]
Hello,

Can you please provide the container logs and a screenshot of the page you mentioned ?

Also, I recommend using the docker-compose template files, for test or for prod, as they will ensure everything is properly configured and easy to maintain.

**Comment by ser-gent** [comment]
Hi,
Sorry for not getting back to you before now !
you have the screenshot here
![Capture du 2019-08-02 12-47-30](https://user-images.githubusercontent.com/35431344/62365254-ee6b4100-b523-11e9-9dcf-4719428b9357.png)
and the container logs
`docker run -e DOLI_AUTO_CONFIGURE='' -p 8080:80 monogramm/docker-dolibarr
Initializing PHP configuration...
Updating Dolibarr users and group...
usermod: no changes
Updating Dolibarr folder ownership...
Initializing Dolibarr HTML configuration directory...
Dolibarr initialization...
Create forced values for first Dolibarr install...
You shall complete Dolibarr install manually at 'http://localhost/install'
Adding a symlink to /var/www/htdocs...
Serving Dolibarr...

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using [IP ADDRESS] Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using [IP ADDRESS] Set the 'ServerName' directive globally to suppress this message
PHP Warning:  Module 'calendar' already loaded in Unknown on line 0
`
*I hide IP address

**Comment by madmath03** [comment]
Sorry @ser-gent for not coming back to you earlier.

From the logs, I can see that the forced values were generated, but it's not a good idea when `DOLI_AUTO_CONFIGURE` is disabled.

I will make a fix that will disable forced values when `DOLI_AUTO_CONFIGURE` is disable.
