### ISSUE TITLE
Php intl (international) function is missing (11)

### ISSUE THREAD

**Issue by bd8392** [Monogramm/docker-dolibarr#59]
The Dolibarr installer complains that the intl extension is missing...

**Comment by madmath03** [comment]
@bd8392 too many unanswered questions with your description to help you properly (what version etc)... please use the issue templates provided

**Comment by bd8392** [comment]
Ok sorry I'm doing with template now =)

**Describe the bug**
Dolibarr install wizard complains that the intl extension of php is missing on install wizard

**To Reproduce**
1. Pull the Monogramm/docker 11.0 and configure it like it the discription, but as swarm stack
2. Set the autoconfigure variable to 0, so you can configure it with setup-wizard
3. on the check-page for installation prerequisites dolibarr complains about the missing intl extension.
4. installation proceeds without error

**Expected behavior**
all extensions should be there

**Docker (please complete the following information):**
19.0.3 in Swarmmode

it appears on desktop and mobile, sadly I can't provide screenshots anymore, because I have it already setup...

Sorry for the Inconnvienience! Next time I use the template right away!

Thanks for this cool docker development =) you're providing the best and most updted container so far =)

**Comment by madmath03** [comment]
Thanks @bd8392 for using the template and the love :-)

intl support should have been added while fixing #56 but I guess some libraries might be missing at runtime.
Will look into that asap.

**Comment by bd8392** [comment]
Cool thanks :-)

**Comment by madmath03** [comment]
@bd8392 Latest PR #60 should have fixed this issue. Pull the latest image and it should be good for you now.

**Comment by bd8392** [comment]
Very cool! Thanks :-)
