### ISSUE TITLE
Add support for v12.0.x to repo and dockerhub

### ISSUE THREAD

**Issue by marcodings** [Monogramm/docker-dolibarr#62]
Hi,

As i'm getting started with dolibarr i wanted to use the latest and greatest using php 7.4.x with dolibar 12.0.1 at the moment of this writing.

With the following modifications to the Dockerfile for apache and php7.2 i seem to have it working. Sharing as it might be of interest to others.

share and enjoy
-- Marco

``` diff
--- Dockerfile	2020-07-12 10:50:20.630819400 +0200
+++ Dockerfile.org	2020-07-12 10:45:12.680819400 +0200
@@ -1,4 +1,4 @@
-FROM php:7.4-apache
+FROM i386/php:7.2-apache
 
 # Install the packages we need
 # Install the PHP extensions we need
@@ -32,13 +32,15 @@
 	; \
 	debMultiarch="$(dpkg-architecture --query DEB_BUILD_MULTIARCH)"; \
 	docker-php-ext-configure ldap --with-libdir="lib/$debMultiarch"; \
-	docker-php-ext-configure gd --with-freetype=/usr  --with-jpeg=/usr; \
+	docker-php-ext-configure gd --with-freetype-dir=/usr --with-png-dir=/usr --with-jpeg-dir=/usr; \
 	docker-php-ext-configure intl; \
+	docker-php-ext-configure zip --with-libzip; \
 	docker-php-ext-install -j "$(nproc)" \
 		calendar \
 		gd \
 		intl \
 		ldap \
+		mbstring \
 		mysqli \
 		pdo \
 		pdo_mysql \
@@ -59,7 +61,7 @@
 # Runtime env var
 ENV DOLI_AUTO_CONFIGURE=1 \
 	DOLI_DB_TYPE=mysqli \
-	DOLI_DB_HOST='' \
+	DOLI_DB_HOST= \
 	DOLI_DB_PORT=3306 \
 	DOLI_DB_USER=dolibarr \
 	DOLI_DB_PASSWORD='' \
@@ -73,7 +75,7 @@
 	DOLI_MODULES='' \
 	DOLI_URL_ROOT='http://localhost' \
 	DOLI_AUTH=dolibarr \
-	DOLI_LDAP_HOST='' \
+	DOLI_LDAP_HOST= \
 	DOLI_LDAP_PORT=389 \
 	DOLI_LDAP_VERSION=3 \
 	DOLI_LDAP_SERVERTYPE=openldap \
@@ -94,7 +96,7 @@
 	PHP_MAX_EXECUTION_TIME=300
 
 # Build time env var
-ARG DOLI_VERSION=12.0.1
+ARG DOLI_VERSION=11.0.3
 
 # Get Dolibarr
 ADD https://github.com/Dolibarr/dolibarr/archive/${DOLI_VERSION}.zip /tmp/dolibarr.zip
```

Rationale for changes can be found here
* [gd has unrecognized options in PHP 7.4](https://github.com/docker-library/php/issues/912)
* [PHP 7.4 ZIP extension option --enable-zip was removed](https://github.com/laradock/laradock/issues/2421)
* [mbstring (already installed](https://github.com/laradock/laradock/issues/2407)
* [Package requirements (oniguruma) were not met](https://stackoverflow.com/questions/59251008/docker-laravel-configure-error-package-requirements-oniguruma-were-not-m/59253249#59253249)

**Comment by ssnobben** [comment]
Is this working with Joomla 3.9.19 and new Joomla 4 Marco??

**Comment by madmath03** [comment]
> Is this working with Joomla 3.9.19 and new Joomla 4 Marco??

what does this have to do with Dolibarr ??

**Comment by madmath03** [comment]
Thanks @marcodings for suggesting this.
Dolibarr 12 added.

PHP 7.4 will not be enabled here since all currently supported versions of Dolibarr do not accept it: https://wiki.dolibarr.org/index.php/Versions

We will upgrade to PHP 7.3 when version 8 of Dolibarr is dropped.

**Comment by ssnobben** [comment]
@marcodings I was thinking the attention & focus was on Joomla4 development & support? 
![Joomla](https://user-images.githubusercontent.com/6490832/87915767-d9f4c100-ca72-11ea-8b42-1ca91e398dbf.jpg)
